# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ALL OS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: ls build
    - name: Upload .7z file (if any exists)
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-compressed.7z
        path: build/*.7z
    - name: Upload .dmg file (if any exists)
      if: ${{ runner.os == 'macOS' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}.dmg
        path: build/*.dmg
    - name: Upload .exe file (if any exists)
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}.exe
        path: build/*.exe    # TODO: should exclude the setup .exe
    - name: Upload .AppImage file (if any exists)
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}.AppImage
        path: build/*.AppImage  